name: ESLint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install ESLint
      run: yarn

    - name: Run ESLint
      run: yarn eslint .
